version: "3"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ["bin/rails", "s", "-b", "0.0.0.0", "-p", "5000"]
    volumes:
      - ./backend:/myapp/backend:cached
      - bundle:/usr/local/bundle
    ports:
      - 5000:5000
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    build: ./front
    command: ["yarn", "start"]
    tty: true
    stdin_open: true
    volumes:
      - ./front:/myapp/front:cached
    ports:
      - 3001:3000

volumes:
  bundle:
    driver: local
  pgdata:
    driver: local
