version: '3'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp/backend
      - bundle:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

  front:
    image: node:12.0.0
    working_dir:
      "/myapp/front/react-app"
    command: bash -c "yarn && yarn start"
    ports:
      - "5000:3000"
    volumes:
     - ./front:/myapp/front/react-app
     - modules:/myapp/front/react-app/node_modules:cached
    tty: true

volumes:
  bundle:
    driver: local
  pgdata:
    driver: local
  modules:
    driver: local
